name: iOS CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: macos-15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: xcodebuild -resolvePackageDependencies
        
      - name: Build and Run Tests
        run: |
          xcodebuild clean test \
            -scheme MediStock \
            -destination 'platform=iOS Simulator,name=iPhone 16,OS=latest' \
            -quiet \
            -resultBundlePath TestResults.xcresult

      # Upload des résultats en cas d'échec pour débugger
      - name: Upload Test Results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: TestResults.xcresult
